server: 
 port: 5001
spring: 
 thymeleaf: 
      cache: false
 profiles: 
    active: dev
email: 
  domain: 
    validate: 
           api: 
             value: https://emailvalidation.abstractapi.com/v1/?api_key=
             key: e2c1b0fea1d2423aad3c7341d8003888
NotEmpty: 
  customer: 
     firstName: First Name must be Provided, It shouldnt be empty

#logging: 
 #  level: 
  #    org.springframework: DEBUG
  
#logging:
 # file:
    #name: application.log
  #  path: ${LOG_FILE_PATH:c:/weshopify-app}
  #logback:
   # rollingpolicy:
      #max-file-size: 1
      #max-history: 3
    #  clean-history-on-start: true

        
---
#Dev Environment Configuration
spring: 
  datasource: 
     driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
     url: jdbc:${DB_TYPE:mysql}://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_SCHEMA:shopifyme-customers}
     #url: jdbc:${DB_TYPE:mysql}://${DB_HOST:weshopify-platform-sg.cci53w9t6upc.ap-southeast-1.rds.amazonaws.com}:${DB_PORT:3306}/${DB_SCHEMA:weshopify_platform}
     username: ${DB_USER_NAME:root} 
     #password: ${DB_USER_PASSWORD:root}
     password: ${DB_USER_PASSWORD:Adance123$}
  jpa: 
    hibernate: 
       ddl-auto: update
    show-sql: true
    properties: 
      hibernate: 
        dialect: ${DB_DIALECT:org.hibernate.dialect.MySQL8Dialect}
  profiles: dev
---
#QA Environment Configurations
spring: 
  h2: 
   console: 
    enabled: true
    path: /h2Console
  profiles: qa            
